from __future__ import annotations

APP_NAME = "ParqScan"
RECENT_FILE_LIMIT = 10

PAGE_SIZE_OPTIONS = (20, 50, 100, 200)
DEFAULT_PAGE_SIZE = 20
PAGE_READ_BATCH_ROWS = 64
PAGE_LOAD_THREADS = 1

THUMBNAIL_SIZE = 72
IMAGE_HOVER_SIZE = 520
IMAGE_HOVER_CACHE_LIMIT = 16
THUMBNAIL_CACHE_LIMIT = 96
DEFAULT_ROW_HEIGHT = 42
IMAGE_ROW_HEIGHT = 88
HEX_BYTES_PER_LINE = 16

EXPORT_BATCH_ROWS = 2048
MEMORY_STATUS_INTERVAL_MS = 1500
SEARCH_DEBOUNCE_MS = 220
